version: '3.7'

services:
  cerebro:
    container_name: cerebro
    image: lmenezes/cerebro:0.9.2
    networks:
      - cerebro
    restart: always
    ports:
      - 9000:9000


networks:
  cerebro:
    external: true
