---
version: '3.7'

services:
  wg-exporter:
    hostname: wg-exporter
    container_name: wg-exporter
    restart: always
    #image: mindflavor/prometheus-wireguard-exporter:3.6.1
    image: yangchuansheng/wireguard_exporter
    network_mode: host
    cap_add:
      - ALL
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: '10m'
    
