---
version: "3"

services:
  gitlab:
    image: 'gitlab/gitlab-ce:12.1.3-ce.0'
    container_name: gitlab
    hostname: gitlab.3day.top
    restart: always

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.3day.top'
        # email setting
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.qiye.aliyun.com"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "server@3day.top"
        gitlab_rails['smtp_password'] = "6Q3BjX5hYLshws9s"
        gitlab_rails['smtp_domain'] = "smtp.qiye.aliyun.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        gitlab_rails['gitlab_email_from'] = 'server@3day.top'
    ports:
      - '80:80'
      - '443:443'
      - '33:22'
    volumes:
      - '/data/gitlab/config:/etc/gitlab'
      - '/data/gitlab/logs:/var/log/gitlab'
      - '/data/gitlab/data:/var/opt/gitlab'

  runner:
    image: gitlab/gitlab-runner:alpine-v12.1.0
    restart: always
    container_name: gitlab_runner
    environment:
      - CI_SERVER_URL=http://gitlab.3day.top/
    volumes:
      - '/data/runner:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock:rw'
