---
version: '3.7'
services:
  mongo:
    hostname: mongo
    container_name: mongo
    image: mongo:4.0.19-xenial
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: hPo72VQIqdTHS8jWuV64
    networks:
      - mongo
    volumes:
      - /data/mongodb:/data/db
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: '5m'

networks:
  mongo:
    external: true
    driver: bridge
